### ISSUE TITLE
"Most referenced nicks" is useless as it fills up with nicknames that are common words.

### ISSUE THREAD

**Issue by Mike13815** [flotwig/StatsBot#5]
The top 5 in techsupport's statistics, for example:

```
Nick    Number of Uses  Last Used by
```

1   The 277301  Mikee
2   a   165556  Mikee
3   my  81446   RoboCop
4   if  49220   NEAL
5   Just    47623   Mikee

**Comment by flotwig** [comment]
This issue arises because people /nick to nicknames which are commonly used words and thereafter, even if they change their nick, any mention of that previous nick will increment the number of mentions.

I'm not sure how to fix this. pisg is used for log processing. If I ignore these nicks as in the [pisg documentation](http://pisg.sourceforge.net/documentation), I believe that it will also ignore anyone who has ever /nicked to The, a, my, if, and Just. This is unacceptable for obvious reasons.

Do you (or anyone) have any ideas? I'm thinking of just removing the Most Referenced Nicks section entirely because this issue is so widespread.

**Comment by sebastianbarfurth** [comment]
I don't believe there is a good solution apart from using an Englisch dictionary to compare nicks against and having a filtering mechanism. Honestly there is hardly a fix for this.
